### ISSUE TITLE
Getting receiving on an empty and disconnected channel running in docker

### ISSUE THREAD

**Issue by punithbm** [romanz/electrs#1055]
Getting following error in the electrs, can you please help me what might be the wrong

electrs error log, 

```
Starting electrs 0.10.5 on x86_64 linux with Config { network: Signet, db_path: "/data/signet", db_log_dir: None, daemon_dir: "/bitcoin/signet", daemon_auth: CookieFile("/bitcoin/.cookie"), daemon_rpc_addr: 68.183.80.225:38332, daemon_p2p_addr: 68.183.80.225:38333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 0.0.0.0:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.10.5 (Electrum Rust Server)!", signet_magic: 0a03cf40, args: [] }
[2024-06-17T17:08:04.305Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 0.0.0.0:4224
[2024-06-17T17:08:04.305Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
[2024-06-17T17:08:04.324Z INFO  electrs::db] "/data/signet": 20 SST files, 0.00002062 GB, 0.00000002 Grows
[2024-06-17T17:08:04.325Z DEBUG electrs::db] DB Some(Config { compacted: false, format: 0 })
[2024-06-17T17:08:04.329Z TRACE electrs::p2p] send: Version(VersionMessage { version: 70001, services: ServiceFlags(0), timestamp: 1718644084, receiver: Address {services: ServiceFlags(NONE), address: 0.0.0.0, port: 0}, sender: Address {services: ServiceFlags(NONE), address: 0.0.0.0, port: 0}, nonce: 11582491815844596145, user_agent: "/electrs:0.10.5/", start_height: 0, relay: false })
[2024-06-17T17:08:04.330Z DEBUG electrs::p2p] closing p2p_recv thread: connection closed
[2024-06-17T17:08:04.330Z DEBUG electrs::p2p] closing p2p_loop thread: peer has disconnected
[2024-06-17T17:08:04.330Z DEBUG electrs::p2p] closing p2p_send thread: no more messages to send
[2024-06-17T17:08:04.330Z INFO  electrs::db] closing DB at /data/signet
Error: electrs failed

Caused by:
    receiving on an empty and disconnected channel
```

**bitcoin.conf file** 

```
signet=1
rpccookiefile=/root/.bitcoin/.cookie
rpcauth=bitcoin:xxxxxxxxxxxxxxxxxxxxxxxxxx
txindex=1
blockfilterindex=1
peerblockfilters=1
coinstatsindex=1
dnsseed=0
persistmempool=1
uacomment=CustomSignet
[signet]
daemon=1
listen=1
server=1
debug=net
discover=1
signetchallenge=512102de2d9ca0a9a584ee89ef099d3c4aff9710e257251c4a030a6fa878b7eecef94751ae
signetblocktime=10
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
zmqpubhashblock=tcp://0.0.0.0:28334
rpcbind=0.0.0.0:38332
rpcallowip=0.0.0.0/0
whitelist=0.0.0.0/0
fallbackfee=0.0002
bind=0.0.0.0
port=38333
```

**Comment by Kixunil** [comment]
Looks like your bitcoind got shutdown, can you check its logs?

**Comment by punithbm** [comment]
No, Its running  - http://68.183.80.225:38332 

<img width="621" alt="Screenshot 2024-06-17 at 11 49 09 PM" src="https://github.com/romanz/electrs/assets/13044958/6a057766-57ea-42db-9d0e-7bec06ecb06c">


wondering what could've gone wrong

**Comment by Kixunil** [comment]
Please check the logs from around 17:08:04, bitcoind should say some reason why it disconnects.

**Comment by punithbm** [comment]
tried again now, same error. How can check the required logs for this ? 

<img width="1527" alt="Screenshot 2024-06-17 at 11 57 17 PM" src="https://github.com/romanz/electrs/assets/13044958/56b396ca-93a7-43d5-810f-537cfe5ecfa1">

**Comment by Kixunil** [comment]
I guess you need to increase verbosity of bitcoind somehow.

**Comment by Kixunil** [comment]
Is it possible that you're missing `signet_magic` configuration option?

**Comment by punithbm** [comment]
but it take default `signet_magic: 0a03cf40` right ?

**Comment by Kixunil** [comment]
Yes but you've set signet challenge which might affect it but I don't really have much knowledge here. Just guessing.

**Comment by punithbm** [comment]
Ok, do you think may be due to this error ? Error: Cannot obtain a lock on data directory /root/.bitcoin/signet. Bitcoin Core is probably already running.

i can see this error on startup.. do you know how to clear that ?

**Comment by antonilol** [comment]
bitcoin core probably disconnects electrs because the network magic is wrong, see https://en.bitcoin.it/wiki/Signet
the magic in the electrs config is the default signet magic, but you use a custom signet challenge, so you need to calculate your own network magic and put it in the config for electrs

**Comment by punithbm** [comment]
Thank you for response, do you know how to calculate our own network magic

**Comment by punithbm** [comment]
its available in the signet debug logs as well, Got it thanks for the help

**Comment by antonilol** [comment]
The same Bitcoin wiki page also mentions how to calculate the megic bytes from the signet challenge, the first 4 bytes of `sha256d(challenge_len || challenge)` (length is encoded as a typical bitcoin consensus varint)

https://en.bitcoin.it/wiki/Signet#Genesis_Block_and_Message_Header

**Comment by riegersan** [comment]
I have the exact same problem on mainnet for some days

`Electrum attempting reconnect...
syncPercent error:  Error: close connect
    at /app/node_modules/@lily-technologies/electrum-client/lib/client.js:230:37
    at Array.forEach (<anonymous>)
    at ElectrumClient.onClose (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:229:44)
    at ElectrumClient.onClose (/app/node_modules/@lily-technologies/electrum-client/index.js:69:9)
    at Socket.<anonymous> (/app/node_modules/@lily-technologies/electrum-client/lib/client.js:60:9)
Starting electrs 0.10.2 on x86_64 linux with Config { network: Bitcoin, db_path: "/data/db/bitcoin", db_log_dir: None, daemon_dir: "/data/.bitcoin", daemon_auth: CookieFile("/data/.bitcoin/.cookie"), daemon_rpc_addr: 10.21.21.8:8332, daemon_p2p_addr: 10.21.21.8:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Umbrel Electrs (0.10.2)", signet_magic: f9beb4d9, args: [] }
[2024-08-26T06:35:54.339Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2024-08-26T06:35:54.339Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
[2024-08-26T06:35:54.368Z INFO  electrs::db] "/data/db/bitcoin": 205 SST files, 49.271868142 GB, 6.15817247 Grows
[2024-08-26T06:35:55.101Z INFO  electrs::chain] loading 857616 headers, tip=000000000000000000000eebdc7d1097dc0caee5d639ba8a7711cc274f6cc923
[2024-08-26T06:35:55.631Z INFO  electrs::chain] chain updated: tip=000000000000000000000eebdc7d1097dc0caee5d639ba8a7711cc274f6cc923, height=857616
[2024-08-26T06:35:55.638Z INFO  electrs::db] closing DB at /data/db/bitcoin
    at Socket.emit (node:events:527:28)
[2024-08-26T06:35:55.638Z WARN  electrs::p2p] failed to shutdown p2p connection: Transport endpoint is not connected (os error 107)
    at TCP.<anonymous> (node:net:709:12)
Error: electrs failed

Caused by:
    receiving on an empty and disconnected channel
Starting electrs 0.10.2 on x86_64 linux with Config { network: Bitcoin, db_path: "/data/db/bitcoin", db_log_dir: None, daemon_dir: "/data/.bitcoin", daemon_auth: CookieFile("/data/.bitcoin/.cookie"), daemon_rpc_addr: 10.21.21.8:8332, daemon_p2p_addr: 10.21.21.8:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Umbrel Electrs (0.10.2)", signet_magic: f9beb4d9, args: [] }
[2024-08-26T06:36:55.881Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2024-08-26T06:36:55.881Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
[2024-08-26T06:36:55.904Z INFO  electrs::db] "/data/db/bitcoin": 206 SST files, 49.27186916 GB, 6.158172471 Grows
[2024-08-26T06:36:56.597Z INFO  electrs::chain] loading 857616 headers, tip=000000000000000000000eebdc7d1097dc0caee5d639ba8a7711cc274f6cc923
[2024-08-26T06:36:57.085Z INFO  electrs::chain] chain updated: tip=000000000000000000000eebdc7d1097dc0caee5d639ba8a7711cc274f6cc923, height=857616
[2024-08-26T06:36:57.091Z WARN  electrs::p2p] failed to shutdown p2p connection: Transport endpoint is not connected (os error 107)
[2024-08-26T06:36:57.091Z INFO  electrs::db] closing DB at /data/db/bitcoin
Error: electrs failed

Caused by:
    receiving on an empty and disconnected channel
::ffff:10.21.0.17 - - [Mon, 26 Aug 2024 06:35:26 GMT] "GET /v1/electrs/syncPercent HTTP/1.1" 500 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15"
`

**Comment by joel-regen** [comment]
I'm having the same issue on Umbrel OS 1.2.2 running on raspberry pi 5:
umbrel@umbrel:~/umbrel$ sudo docker logs 2a9f90fd3169 | tail -50
Starting electrs 0.10.6 on aarch64 linux with Config { network: Bitcoin, db_path: "/data/db/bitcoin", db_log_dir: None, daemon_dir: "/data/.bitcoin", daemon_auth: CookieFile("/data/.bitcoin/.cookie"), daemon_rpc_addr: 10.21.21.8:8332, daemon_p2p_addr: 10.21.21.8:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Umbrel Electrs (0.10.6)", signet_magic: f9beb4d9 }
[2024-11-16T11:34:01.039Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2024-11-16T11:34:01.039Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
[2024-11-16T11:34:01.103Z INFO  electrs::db] "/data/db/bitcoin": 99 SST files, 0.00010076 GB, 0.000000021 Grows
[2024-11-16T11:34:01.119Z WARN  electrs::thread] p2p_recv thread failed: failed to recv a message from peer: IO error
[2024-11-16T11:34:01.120Z INFO  electrs::db] closing DB at /data/db/bitcoin
[2024-11-16T11:34:01.120Z WARN  electrs::p2p] failed to shutdown p2p connection: Transport endpoint is not connected (os error 107)
Error: electrs failed

Caused by:
    receiving on an empty and disconnected channel
Starting electrs 0.10.6 on aarch64 linux with Config { network: Bitcoin, db_path: "/data/db/bitcoin", db_log_dir: None, daemon_dir: "/data/.bitcoin", daemon_auth: CookieFile("/data/.bitcoin/.cookie"), daemon_rpc_addr: 10.21.21.8:8332, daemon_p2p_addr: 10.21.21.8:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Umbrel Electrs (0.10.6)", signet_magic: f9beb4d9 }
[2024-11-16T11:34:01.777Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2024-11-16T11:34:01.777Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
[2024-11-16T11:34:01.825Z INFO  electrs::db] "/data/db/bitcoin": 100 SST files, 0.000101778 GB, 0.000000021 Grows
[2024-11-16T11:34:01.840Z INFO  electrs::db] closing DB at /data/db/bitcoin
[2024-11-16T11:34:01.840Z WARN  electrs::p2p] failed to shutdown p2p connection: Transport endpoint is not connected (os error 107)
Error: electrs failed

**Comment by jblachly** [comment]
Same issue, linux, neither bitcoind nor electrs in Docker; both mainnet. Has been running for a week or so without issue then suddenly barfing today.

```
[2025-10-20T23:43:33.518Z INFO  electrs::index] indexing 1 blocks: [920017..920017]
[2025-10-20T23:43:33.555Z INFO  electrs::chain] chain updated: tip=0000000000000000000119d0925b704f64c9f82f14dafe0756c115cc8b94cfcd, height=920017
[2025-10-20T23:44:10.448Z INFO  electrs::index] indexing 1 blocks: [920018..920018]
[2025-10-20T23:44:10.512Z INFO  electrs::chain] chain updated: tip=000000000000000000001b673ff41ba530ceb3585ff2d31ccf431e8ddbeec47f, height=920018
[2025-10-20T23:44:13.849Z WARN  electrs::thread] p2p_send thread failed: p2p failed to send
[2025-10-20T23:44:13.849Z WARN  electrs::thread] because: Broken pipe (os error 32)
[2025-10-20T23:44:13.849Z WARN  electrs::electrum] RPC blockchain.scripthash.subscribe failed: sending on a disconnected channel
[2025-10-20T23:44:13.849Z WARN  electrs::electrum] RPC blockchain.scripthash.subscribe failed: failed to get block 00000000000000000002d57ffa33607da376a83fcc74377cff68d7ce5e81e7d0: receiving on an empty and disconnected channel
[2025-10-20T23:44:13.850Z WARN  electrs::electrum] RPC blockchain.scripthash.subscribe failed: sending on a disconnected channel
[2025-10-20T23:44:13.850Z INFO  electrs::db] closing DB at /home/james/.electrs/data/bitcoin
Error: electrs failed

Caused by:
    0: sync failed
    1: sending on a disconnected channel
james@nuc8i7hvk:~/src/electrs$ target/release/electrs
Starting electrs 0.10.10 on x86_64 linux with Config { network: Bitcoin, db_path: "/home/james/.electrs/data/bitcoin", db_log_dir: None, db_parallelism: 1, daemon_auth: CookieFile("/home/james/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 0.0.0.0:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.10.10 (Electrum Rust Server)!", signet_magic: f9beb4d9 }
[2025-10-20T23:45:37.845Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2025-10-20T23:45:37.845Z INFO  electrs::server] serving Electrum RPC on 0.0.0.0:50001
[2025-10-20T23:45:37.916Z INFO  electrs::db] "/home/james/.electrs/data/bitcoin": 225 SST files, 57.040549704 GB, 7.10939788 Grows
[2025-10-20T23:45:39.557Z INFO  electrs::chain] loading 920018 headers, tip=000000000000000000001b673ff41ba530ceb3585ff2d31ccf431e8ddbeec47f
[2025-10-20T23:45:41.494Z INFO  electrs::chain] chain updated: tip=000000000000000000001b673ff41ba530ceb3585ff2d31ccf431e8ddbeec47f, height=920018
[2025-10-20T23:53:22.656Z INFO  electrs::index] indexing 1 blocks: [920019..920019]
[2025-10-20T23:53:22.693Z INFO  electrs::chain] chain updated: tip=00000000000000000001676a708f68d8ad8c8f8af4c17df0942e22737be4f44f, height=920019
[2025-10-20T23:53:25.295Z WARN  electrs::electrum] RPC blockchain.transaction.get failed: failed to get transaction: JSON-RPC error: RPC error response: RpcError { code: -5, message: "No such mempool or blockchain transaction. Use gettransaction for wallet transactions.", data: None }
[2025-10-21T00:06:32.669Z INFO  electrs::index] indexing 1 blocks: [920020..920020]
[2025-10-21T00:06:32.698Z INFO  electrs::chain] chain updated: tip=00000000000000000000b1c0707d118f899b5087e4c4017f1ed742a97620940e, height=920020
[2025-10-21T00:10:31.458Z INFO  electrs::index] indexing 1 blocks: [920021..920021]
[2025-10-21T00:10:31.492Z INFO  electrs::chain] chain updated: tip=0000000000000000000191348f91f15ef88e9bed459c8f462e4facb75ed422b4, height=920021
[2025-10-21T00:10:34.140Z WARN  electrs::electrum] RPC blockchain.scripthash.subscribe failed: failed to get block 00000000000000000002d57ffa33607da376a83fcc74377cff68d7ce5e81e7d0: receiving on an empty and disconnected channel
[2025-10-21T00:10:34.140Z WARN  electrs::electrum] RPC blockchain.scripthash.subscribe failed: sending on a disconnected channel
[2025-10-21T00:10:34.140Z WARN  electrs::electrum] RPC blockchain.scripthash.subscribe failed: sending on a disconnected channel
[2025-10-21T00:10:34.140Z INFO  electrs::db] closing DB at /home/james/.electrs/data/bitcoin
Error: electrs failed

Caused by:
    0: sync failed
    1: sending on a disconnected channel
```

**Comment by mariodian** [comment]
I have the same issue (manual install). Bitcoin is running fine. It’s definitely triggered by Sparrow (any Electrum client really), but in my case, it also happens spontaneously.

In addition to the already reported error, I occasionally get the following too:

```
2026-04-20T11:20:48.047680+08:00 nuc13 electrs[1281139]: Starting electrs 0.11.1 on x86_64 linux with Config { network: Bitcoin, db_path: "./db/bitcoin", db_log_dir: None, db_parallelism: 1, daemon_auth: CookieFile("/home/satoshi/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 127.0.0.1:51001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Welcome to electrum server!", magic: f9beb4d9 }
2026-04-20T11:20:48.047866+08:00 nuc13 electrs[1281139]: [2026-04-20T03:20:48.047Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
2026-04-20T11:20:48.047897+08:00 nuc13 electrs[1281139]: [2026-04-20T03:20:48.047Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:51001
2026-04-20T11:20:48.142028+08:00 nuc13 electrs[1281139]: [2026-04-20T03:20:48.141Z INFO  electrs::db] "./db/bitcoin": 261 SST files, 60.372425171 GB, 7.486956405 Grows
2026-04-20T11:20:49.165507+08:00 nuc13 electrs[1281139]: [2026-04-20T03:20:49.165Z INFO  electrs::chain] loading 945880 headers, tip=0000000000000000000006300a1c161a9e355b4738b9149ee8859f121d7f83da
2026-04-20T11:20:49.823522+08:00 nuc13 electrs[1281139]: [2026-04-20T03:20:49.823Z INFO  electrs::chain] chain updated: tip=0000000000000000000006300a1c161a9e355b4738b9149ee8859f121d7f83da, height=945880
2026-04-20T11:23:31.894711+08:00 nuc13 electrs[1281139]: [2026-04-20T03:23:31.894Z INFO  electrs::index] indexing 1 blocks: [945881..945881]
2026-04-20T11:23:31.947182+08:00 nuc13 electrs[1281139]: [2026-04-20T03:23:31.947Z INFO  electrs::chain] chain updated: tip=000000000000000000008391badfc1099ec271a843e8bee7a0581e09526223f4, height=945881
2026-04-20T11:23:33.156824+08:00 nuc13 electrs[1281139]: [2026-04-20T03:23:33.156Z WARN  electrs::thread] p2p_send thread failed: p2p failed to send
2026-04-20T11:23:33.156960+08:00 nuc13 electrs[1281139]: [2026-04-20T03:23:33.156Z WARN  electrs::thread] because: Connection reset by peer (os error 104)
2026-04-20T11:23:33.158237+08:00 nuc13 electrs[1281139]: [2026-04-20T03:23:33.158Z WARN  electrs::electrum] RPC blockchain.scripthash.subscribe failed: sending on a disconnected channel
2026-04-20T11:23:33.158304+08:00 nuc13 electrs[1281139]: thread 'main' panicked at src/electrum.rs:369:26:
2026-04-20T11:23:33.158324+08:00 nuc13 electrs[1281139]: missing scripthash status
2026-04-20T11:23:33.158339+08:00 nuc13 electrs[1281139]: stack backtrace:
2026-04-20T11:23:33.160048+08:00 nuc13 electrs[1281139]:    0: __rustc::rust_begin_unwind
2026-04-20T11:23:33.160087+08:00 nuc13 electrs[1281139]:    1: core::panicking::panic_fmt
2026-04-20T11:23:33.160132+08:00 nuc13 electrs[1281139]:    2: core::option::expect_failed
2026-04-20T11:23:33.160151+08:00 nuc13 electrs[1281139]:    3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
2026-04-20T11:23:33.160168+08:00 nuc13 electrs[1281139]:    4: electrs::server::run
2026-04-20T11:23:33.203151+08:00 nuc13 electrs[1281139]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2026-04-20T11:23:33.204867+08:00 nuc13 electrs[1281139]: [2026-04-20T03:23:33.204Z INFO  electrs::db] closing DB at ./db/bitcoin
2026-04-20T11:23:33.268345+08:00 nuc13 systemd[1]: electrs.service: Main process exited, code=exited, status=101/n/a
2026-04-20T11:23:33.278793+08:00 nuc13 systemd[1]: electrs.service: Failed with result 'exit-code'.
2026-04-20T11:23:33.278889+08:00 nuc13 systemd[1]: electrs.service: Consumed 13.784s CPU time.
2026-04-20T11:24:33.270154+08:00 nuc13 systemd[1]: electrs.service: Scheduled restart job, restart counter is at 7.
2026-04-20T11:24:33.287322+08:00 nuc13 systemd[1]: Started electrs.service - Electrs.
```

`RUST_BACKTRACE=full` doesn't return anything beyond what you already see.

It's been like this for at least a year.
