### ISSUE TITLE
Docker electrs won't compile blocks

### ISSUE THREAD

**Issue by BTCxZelko** [romanz/electrs#214]
So i'm running electrs in a docker connected via RPC cookie in electrs.toml
I have index-batch-size=10 via parameters...but this is my output that shuts down and then restarts over and over:

```
Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Never }, network_type: bitcoin, db_path: "/home/user/db/mainnet", daemon_dir: "/home/user/.bitcoin", daemon_rpc_addr: V4(172.28.1.5:28256), electrum_rpc_addr: V4(172.28.1.10:50001), monitoring_addr: V4(127.0.0.1:4224), jsonrpc_import: false, index_batch_size: 100, bulk_index_threads: 4, tx_cache_size: 10485760, txid_limit: 100, server_banner: "Welcome to electrs 0.8.2 (Electrum Rust Server)!", blocktxids_cache_size: 10485760 }
2020-01-16T06:57:47.248+00:00 - DEBUG - Server listening on 127.0.0.1:4224
2020-01-16T06:57:47.250+00:00 - DEBUG - Running accept thread
2020-01-16T06:57:47.252+00:00 - INFO - NetworkInfo { version: 190001, subversion: "/Satoshi:0.19.0.1/" }
2020-01-16T06:57:47.253+00:00 - INFO - BlockchainInfo { chain: "main", blocks: 613055, headers: 613055, bestblockhash: "000000000000000000122df7aa52e431323eb661ea54b2b79b1257e8e238e0ba", pruned: false, initialblockdownload: false }
2020-01-16T06:57:47.254+00:00 - DEBUG - opening DB at "/home/user/db/mainnet"
2020-01-16T06:57:47.297+00:00 - TRACE - lastest indexed blockhash: 0000000000000000000000000000000000000000000000000000000000000000
2020-01-16T06:57:47.297+00:00 - INFO - listing block files at "/home/user/.bitcoin/blocks/blk*.dat"
2020-01-16T06:57:47.297+00:00 - INFO - indexing 0 blk*.dat files
2020-01-16T06:57:47.297+00:00 - DEBUG - found 0 indexed blocks
2020-01-16T06:57:47.309+00:00 - TRACE - downloading 100000 block headers
2020-01-16T06:57:57.905+00:00 - TRACE - downloading 100000 block headers
2020-01-16T06:58:08.492+00:00 - TRACE - downloading 100000 block headers
2020-01-16T06:58:18.850+00:00 - TRACE - downloading 100000 block headers
2020-01-16T06:58:29.500+00:00 - TRACE - downloading 100000 block headers
2020-01-16T06:58:40.160+00:00 - TRACE - downloading 100000 block headers
2020-01-16T06:58:50.697+00:00 - TRACE - downloading 13056 block headers
2020-01-16T06:58:56.274+00:00 - DEBUG - applying 613056 new headers from height 0
2020-01-16T06:58:56.751+00:00 - DEBUG - no more blocks to index
2020-01-16T06:58:56.751+00:00 - DEBUG - no more blocks to index
2020-01-16T06:58:56.752+00:00 - DEBUG - no more blocks to index
2020-01-16T06:58:56.753+00:00 - DEBUG - no more blocks to index
thread 'bulk_writer' panicked at 'no indexed header found', src/libcore/option.rs:1185:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
2020-01-16T06:58:56.755+00:00 - TRACE - closing DB at "/home/user/db/mainnet"
thread 'main' panicked at 'writer panicked: Any', src/libcore/result.rs:1165:5
```

Not sure where to move from here. Any guidance would be appreciated

**Comment by fkueen** [comment]
@BTCxZelko Try to add following command line parameters to electrs `--index-batch-size=10 --jsonrpc-import`

**Comment by BTCxZelko** [comment]
Fixed with jsonrpc-import

Thank you! Closing

**Comment by BTCxZelko** [comment]
A separate issue but, after compression is complete I'm attempting to connect to the server via tor hidden service and getting the follow:

```
TRACE - RPC Request("{\"jsonrpc\":\"2.0\",\"method\":\"server.ping\",\"params\":[],\"id\":6903}\n")
```
Assuming this is saying that the server is being pinged but not connecting?
 
I appreciate any help

**Comment by romanz** [comment]
Let's open a new issue, with the full verbose log (if possible).
