### ISSUE TITLE
unable to compile librocksdb-sys v5.18.5 on FreeBSD 12.2

### ISSUE THREAD

**Issue by seth586** [romanz/electrs#328]
Errors:
```
error: failed to run custom build command for `librocksdb-sys v5.18.5`

Caused by:
  process didn't exit successfully: `/root/electrs/target/release/build/librocksdb-sys-670fcde5b2a4d7aa/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=rocksdb/
  TARGET = Some("x86_64-unknown-freebsd")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-freebsd")
  CXX_x86_64-unknown-freebsd = None
  CXX_x86_64_unknown_freebsd = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-freebsd = None
  CXXFLAGS_x86_64_unknown_freebsd = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.7.0/fused-src/" "-I" "snappy/" "-I" "lz4/lib/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "zlib/" "-I" "bzip2/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DLZ4=1" "-DZSTD=1" "-DZLIB=1" "-DBZIP2=1" "-DNDEBUG=1" "-DOS_FREEBSD=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/root/electrs/target/release/build/librocksdb-sys-054f1466d6328517/out/rocksdb/cache/clock_cache.o" "-c" "rocksdb/cache/clock_cache.cc"
```

Tried the following with `setenv RUST_BACKTRACE full`
```
Compiling librocksdb-sys v6.11.4 (/root/rust-rocksdb/librocksdb-sys)
     Running `/root/rust-rocksdb/target/debug/build/librocksdb-sys-28d20c1ebde04775/build-script-build`
error: failed to run custom build command for `librocksdb-sys v6.11.4 (/root/rust-rocksdb/librocksdb-sys)`

Caused by:
  process didn't exit successfully: `/root/rust-rocksdb/target/debug/build/librocksdb-sys-28d20c1ebde04775/build-script-build` (exit code: 101)
  --- stderr
  error: header 'rocksdb/include/rocksdb/c.h' does not exist.
  thread 'main' panicked at 'unable to generate rocksdb bindings: ()', librocksdb-sys/build.rs:44:10
  stack backtrace:
     0:          0x18e64ab - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbfb21528b57bb683
     1:          0x190f19d - core::fmt::write::h25441dacb58eb36d
     2:          0x18e1024 - std::io::Write::write_fmt::h972a8e29d46404ab
     3:          0x18dcd68 - std::panicking::default_hook::{{closure}}::h6c84cf1e5de20d49
     4:          0x18dca9a - std::panicking::default_hook::h3042cd1e02830f82
     5:          0x18dd376 - std::panicking::rust_panic_with_hook::h5da942cdef772be8
     6:          0x18dcf6c - rust_begin_unwind
     7:          0x190de10 - core::panicking::panic_fmt::h84d7dd8bb9eb4ac2
     8:          0x190de96 - core::result::unwrap_failed::ha08b463263a68dfd
     9:          0x131d966 - core::result::Result<T,E>::expect::h68bd07238c3e7f4c
                                 at /wrkdirs/usr/ports/lang/rust/work/rustc-1.46.0-src/src/libcore/result.rs:963
    10:          0x131e696 - build_script_build::bindgen_rocksdb::h3b1677a941968608
                                 at librocksdb-sys/build.rs:37
    11:          0x1320e60 - build_script_build::main::hf210f5f9cdf933f8
                                 at librocksdb-sys/build.rs:332
    12:          0x1324d5e - std::rt::lang_start::{{closure}}::he2ac18c7542f4d3f
                                 at /wrkdirs/usr/ports/lang/rust/work/rustc-1.46.0-src/src/libstd/rt.rs:67
    13:          0x18d8e99 - std::rt::lang_start_internal::h9a459f516f91e359
    14:          0x1324d42 - std::rt::lang_start::h989cd4e9c28c7229
                                 at /wrkdirs/usr/ports/lang/rust/work/rustc-1.46.0-src/src/libstd/rt.rs:67
    15:          0x13214db - main
    16:          0x131d2d2 - _start
                                 at /usr/src/lib/csu/amd64/crt1.c:76

```

**Comment by seth586** [comment]
Based on some google-fu, I believe this is due to the `warning: definition of implicit copy constructor for 'FileDescriptor' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]` warning generated by newer versions of clang.

FreeBSD's base compiler is llvm10. The fix is to use version 9 or older. Downgrading resulted in a successful compile. 

To downgrade the default compiler on FreeBSD, use the following steps:

```
pkg install llvm90
ln /usr/local/llvm90/bin/clang++ /usr/local/llvm90/bin/c++
```
then add the llvm90 bin directory to a priority position in your shell's path. Example for csh: `nano ~/.cshrc`:
```
set path = (/usr/local/llvm90/bin /sbin /bin /usr/sbin /usr/bin /usr/local/sbin /usr/local/bin $HOME/bin)
```
Exit and re-enter your shell. Running `c++ --verison` should now show 
```
clang version 9.0.1
```
