### ISSUE TITLE
Bug: contrib/xpub.py doesn't work

### ISSUE THREAD

**Issue by flepied** [romanz/electrs#549]
**Describe the bug**

./contrib/xpub.py doesn't work

**Electrs version**

commit e76b9df1d750286316faccb589171034b0e1fdca

**To Reproduce**
1. Configure and start electrs
2. ./contrib/xpub.py <xpub>
3. See error

**Expected behavior**

complete balance output

**Configuration**

<details>
<summary>electrs.toml</summary>

```
Traceback (most recent call last):
  File "/home/fred/external/electrs/contrib/./xpub.py", line 54, in <module>
    main()
  File "/home/fred/external/electrs/contrib/./xpub.py", line 35, in main
    log.debug('{}', conn.call('blockchain.scripthash.get_history',
TypeError: call() takes 2 positional arguments but 3 were given
```

</details>

**Additional context**

I tried to fix the problem with the following fix:

```
--- contrib/xpub.py
+++ contrib/xpub.py
@@ -32,10 +32,10 @@ def main():
             address = xpub.subkey(change).subkey(n).address()
             script = network.parse.address(address).script()
             script_hash = hashlib.sha256(script).digest()[::-1].hex()
-            log.debug('{}', conn.call('blockchain.scripthash.get_history',
-                                      script_hash))
-            reply = conn.call('blockchain.scripthash.get_balance', script_hash)
-            result = reply['result']
+            result, = conn.call(
+                [client.request('blockchain.scripthash.get_balance',
+                                script_hash)])
+            log.debug('{}/{} -> {}', change, script_hash, result)
             confirmed = result['confirmed'] / 1e8
             total += confirmed
             if confirmed:
```

there is no more traceback but the balance is 0 with my xpub so my fix doesn't seem correct.

**Comment by romanz** [comment]
Many thanks for reporting this issue!
After fixing the issue, this seems to be working on [a "public" xpub](https://github.com/romanz/electrs/issues/539#issuecomment-940229419):
```
$ ./xpub.py xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy
[2021-10-14 05:58:23.331756] INFO: xpub: 0/0: 1JAd7XCBzGudGpJQSDSfpmJhiygtLQWaGL -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:23.461665] INFO: xpub: 0/1: 1GWFxtwWmNVqotUPXLcKVL2mUKpshuJYo -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:23.514382] INFO: xpub: 0/2: 1Eni8JFS4yA2wJkicc3yx3QzCNzopLybCM -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:23.639008] INFO: xpub: 0/3: 124dT55Jqpj9AKTyJnTX6G8RkUs7ReTzun -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:23.807648] INFO: xpub: 0/4: 15T9DSqc6wjkPxcr2MNVSzF9JAePdvS3n1 -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:23.961397] INFO: xpub: 0/5: 1GA9u9TfCG7SWmKCveBumdA1TZpfom6ZdJ -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:24.138483] INFO: xpub: 0/6: 1PogPE3bXc84abzEuM2rJEZf2vCbCEZzXz -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:24.271205] INFO: xpub: 0/7: 176U2WABbj4h5PCrxE963wmxzXd2Mw6bP4 -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:24.406029] INFO: xpub: 0/8: 1HRZDR7CmLnq59w6mtzNa7SHtVWPSxdgKA -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
[2021-10-14 05:58:24.571832] INFO: xpub: 0/9: 1MPdvYLzcekvEzAB7DmiHa1oU8Foh4KUw8 -> 0 BTC confirmed, 0 BTC unconfirmed, 2 txs
```

**Comment by romanz** [comment]
Pushed a small fix for testnet/regtest support: 2ce22bd
It seems to work for the following testnet wallet:
```
$ ./xpub.py --network testnet tpubDC7S4QciHbBjtWNt9KtBpX6J91hcmHPP1CqDPiiu11jzaMZn1Y98wKSakZkbXjvmDvkBHi6hkeT9LwcinCsW1pKmChWKCC2mjdLnhSVQZvR
[2021-10-14 15:45:16.696929] INFO: xpub: 0/0: mpSrK63AX1b6cA9dkTuvEcqdKADd1zZJtA -> 20000 BTC confirmed, 0 BTC unconfirmed, 1 txs
[2021-10-14 15:45:16.704455] INFO: xpub: 0/1: mySfPAESLe4RBPbbSivSoAEf1Ui3cE7nw5 -> 30000 BTC confirmed, 0 BTC unconfirmed, 1 txs
[2021-10-14 15:45:16.711309] INFO: xpub: 0/2: mfuAEqCHzvktCKNLYnUQU1P89T1gncb6nN -> 49198 BTC confirmed, -49198 BTC unconfirmed, 2 txs
[2021-10-14 15:45:16.721355] INFO: xpub: 0/3: my2wU7ceFTm9GJTessv8g8FHXCWZ2d4R7o -> 0 BTC confirmed, 40000 BTC unconfirmed, 1 txs
[2021-10-14 15:45:16.725136] INFO: xpub: 0/4: mp22qi1zSr6wZ8kapLeuaRG1GfBNVJJFiM -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.735178] INFO: xpub: 0/5: myVRZr6n2ghcrnqw9ixmpFS99u3XZWGKvQ -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.744958] INFO: xpub: 0/6: mqc2Zhic2AfdRRJdF2dZnTAEv1e7iHLWy2 -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.748035] INFO: xpub: 0/7: mzpHK2G4kkrV5RXZbYpp2ygboXxnJujLGu -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.751199] INFO: xpub: 0/8: mogXs42jQuUzka8H8q42eXQJWNoJivp9wq -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.754238] INFO: xpub: 0/9: mmJNAv6R7XRS7e5ggmrVEwRyV5NM1Ldjf8 -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.757191] INFO: xpub: 0/10: myArdPc79QjX2NGrZqZJ1YiZWhGVKtctVc -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.759708] INFO: xpub: 0/11: mgLTReycHxvv8jgHAXJd88iivSikMwT7Nq -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.762441] INFO: xpub: 0/12: moGMrjpCHdQfneSTcbDUSdRWCHD4TK4tzp -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.765070] INFO: xpub: 0/13: mqRukPZGwotNizg5oKL1gYdZ7pxGipoKVw -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.774717] INFO: xpub: 0/14: mmnJCCfVnhHASxxE2nUb3nmVWZ4BgYeH6e -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.777710] INFO: xpub: 0/15: mxbvY8s1wqKyiec6Dw1x3fyAvisPGVTiCu -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.786636] INFO: xpub: 0/16: n2NmKFpZLUtUndw3Z4wyLRkB83kRVbnWzZ -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.794250] INFO: xpub: 0/17: mgK3PrEUdqTpPaco26uUB1LHoGK5jdBwkm -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.797407] INFO: xpub: 0/18: n363qaEhRa1dj8u1H9KRd5whkcxsEo3yGC -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.800604] INFO: xpub: 0/19: muRfJGKjhjBfXJHbKqcmsNc2uojcXfZrCE -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.812910] INFO: xpub: 0/20: n35e2YgyHe9PK51Pt3bEKEEJiAYftsr4Nk -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.815885] INFO: xpub: 0/21: mvL9GwmFrxSpk4UfErDv9cFHyqWaKxdBKv -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.831656] INFO: xpub: 0/22: mkmXpUXEVPy8kcEHudVtq523FvcDNcUvBY -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.860109] INFO: xpub: 0/23: mhoKa8VS55NccHui9e7J5GfA3BcMFEypv6 -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.864524] INFO: xpub: 1/0: mjxWFps7crhuKFPKExVxraUKNhhsLnmXQF -> 0 BTC confirmed, 8746 BTC unconfirmed, 1 txs
[2021-10-14 15:45:16.867864] INFO: xpub: 1/1: mwJDGkxi3Bf82SZFGGrawpimbmDPL8RA37 -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.877864] INFO: xpub: 1/2: mr6WmrKJPyfdjcrwSrZkqYN4jVJRdFHZ1d -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.888972] INFO: xpub: 1/3: myx3cttUK8itJeiB8DMHVaFKDfujJkSwbQ -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.892011] INFO: xpub: 1/4: mxMQf9nDyPPmmnZUn1B5yuoSExikUe6Dom -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.895206] INFO: xpub: 1/5: mtBW1WHmn8vq6tshWL3PzpCW8RBJH77Bnz -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.897963] INFO: xpub: 1/6: mnHnFUYYeJc8WGs4uECoWNKHKUzUapPKrF -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.900594] INFO: xpub: 1/7: mfySKQFHvByCf5YKTAMzgGTXMkuQtirwcB -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.903179] INFO: xpub: 1/8: mq9vB3s96xywkVcJT6eM4daFLdambdMXPh -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.905813] INFO: xpub: 1/9: n4ipjqhkZ1CedAoNS3Mnf28yacQ5H5mMaB -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.908534] INFO: xpub: 1/10: msDaZAhL5ZKyEmipeqNCzWcndspyYniB6V -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.918262] INFO: xpub: 1/11: mweysneWEdcibvUvkCsfAm1Xb1HaaPiDZ5 -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.926885] INFO: xpub: 1/12: mfasLKPoV4s6quiKLiLhpcno3Yb1VeLg9a -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.929600] INFO: xpub: 1/13: mqie4HeJ7M9uavxUDkgjVWiJKHDKfzyauQ -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.932513] INFO: xpub: 1/14: mhXAC3dbMrNsTvnYmpomiKeV2Ep8FHtQrT -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.935334] INFO: xpub: 1/15: mxCNrWx7FQxJyrP8j4w7G7yVVsxPD2Jex3 -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.938092] INFO: xpub: 1/16: mvYXwR4YmqtCj2BHKJUac6hXTrHJoBLoBv -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.947937] INFO: xpub: 1/17: n4G3UhP2Fmfs3pjf6zBtZWdSBgg8pF1xjk -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.950601] INFO: xpub: 1/18: mgxER5PFE7aRCeDbxiFYDkq4ZraDFJULBz -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.953283] INFO: xpub: 1/19: mw6iCZdKXSvfjRwL75tfPUAEdzVdzWqC2d -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.970113] INFO: xpub: 1/20: n4NfE4bQHZ2U3fUuLzQT3twA3MT2pY9pJL -> 0 BTC confirmed, 0 BTC unconfirmed, 0 txs
[2021-10-14 15:45:16.970188] INFO: xpub: total balance: 0.00099198 BTC
```

**Comment by romanz** [comment]
IIRC, `pycoin` doesn't support ypub/zpub (but I may be wrong...)

**Comment by romanz** [comment]
Maybe the latest `pycoin` release would work:
https://github.com/richardkiss/pycoin/blob/main/CHANGES

**Comment by flepied** [comment]
I tried to make xpub.py work in ypub/zpub in https://github.com/romanz/electrs/pull/559
