### ISSUE TITLE
Compile error: > error: failed to run custom build command for `librocksdb-sys v5.14.2`

### ISSUE THREAD

**Issue by duckartes** [romanz/electrs#55]
```
   Compiling librocksdb-sys v5.14.2
error: failed to run custom build command for `librocksdb-sys v5.14.2`
process didn't exit successfully: `/mnt/storage/.pin0de/src/github.com/romanz/electrs/target/release/build/librocksdb-sys-75503bf7a5321165/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/

--- stderr
rocksdb/include/rocksdb/c.h:48:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
rocksdb/include/rocksdb/c.h:68:10: fatal error: 'stdarg.h' file not found
rocksdb/include/rocksdb/c.h:48:9: warning: #pragma once in main file [-Wpragma-once-outside-header], err: false
rocksdb/include/rocksdb/c.h:68:10: fatal error: 'stdarg.h' file not found, err: true
thread 'main' panicked at 'unable to generate rocksdb bindings: ()', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::panicking::try
             at libstd/panicking.rs:289
  14: std::rt::lang_start_internal
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: main
  16: __libc_start_main

```

rustc --version
rustc 1.28.0 (9634041f0 2018-07-30)

**Comment by romanz** [comment]
Thanks for reporting this issue!
Did this happen also on previous `electrs` versions?

**Comment by duckartes** [comment]
Nope. Only been having issues compiling recently. 

All issues before were RAM related which I haven't been able to test again :p

**Comment by greenaddress** [comment]
@duckartes is this on arm? arm64? what distro?

**Comment by romanz** [comment]
Following https://askubuntu.com/questions/905205/installing-clang-5-0-and-using-c17, what version of clang are you using?
```
$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by romanz** [comment]
Also, could you please re-run the build with higher verbosity, and attach the result?
```bash
$ cargo build --verbose
```

**Comment by duckartes** [comment]
Raspbian Stretch, 32bit. 

```
clang --version
clang version 3.8.1-24+rpi1 (tags/RELEASE_381/final)
Target: armv6--linux-gnueabihf
Thread model: posix
```

**Comment by duckartes** [comment]
I'm not sure what the issue was... or what I did... but it's running now... 

```
/run.sh
==> /mnt/storage/.pin0de/electrs/electrs.log <==
    Finished release [optimized] target(s) in 5.47s
    Finished release [optimized] target(s) in 1.41s
     Running `target/release/electrs --db-dir=/mnt/storage/.pin0de/electrs/`
```

**Comment by duckartes** [comment]
It compiled and I let it run over night. 

This is what I woke up to. 

cat run.sh
```
#!/bin/bash
set -eu
trap 'kill $(jobs -p)' EXIT

DELAY=5
LOG=/mnt/storage/.pin0de/electrs/electrs.log
CARGO="cargo +stable"

tail -v -n0 -F "$LOG" &

export RUST_BACKTRACE=1
while :
do
        $CARGO fmt
        $CARGO check --release
        $CARGO run --release -- --skip-bulk-import --db-dir=/mnt/storage/.pin0de/electrs/ $* 2>> "$LOG"
        echo "Restarting in $DELAY seconds..."
        sleep $DELAY
done
```


```
ERROR - server failed: Error: RPC failed: [{"id":3691,"method":"getblock","params":["000000000000000014c8d93d4e3ee5065d49eeed1eff83c226b450f7b20492be",false]},{"id":3691,"method":"getblock","params":["000000000000000007f3ec658327af8d92ef4679b7d38df107fb68767a255ec1",false]},{"id":3691,"method":"getblock","params":["000000000000000006e1c8a4f78f2b754941bb6cd0153218d39599133f9a5d24",false]},{"id":3691,"method":"getblock","params":["000000000000000009f1ab36df4f7de1377809ec0a3b95b8dc81dfa0d6f16cab",false]},{"id":3691,"method":"getblock","params":["0000000000000000144b7171c62a27a47fa814d0a7b0599bafaf912fc7f9e286",false]},{"id":3691,"method":"getblock","params":["0000000000000000091a68f51ab5ecdb739384f46462484c0fdb82f0fe256a0b",false]},{"id":3691,"method":"getblock","params":["000000000000000006c950472ba5e3497e02be7d49c96838897b51a0e8cfb3c4",false]},{"id":3691,"method":"getblock","params":["000000000000000008826ef13daf7c169ad0350037eccbc61c9d223bd3c7a37f",false]},{"id":3691,"method":"getblock","params":["000000000000000001d02a51c598404ab0a017294f8356bc94e8e25fda16a78b",false]},{"id":3691,"method":"getblock","params":["000000000000000004553c9437d2052deb9f08015a76257275b71fdc8a9b3cea",false]},{"id":3691,"method":"getblock","params":["000000000000000002d7dbb6a288734ff1a9c36f66b886ed2c20416fb1c1dd8d",false]},{"id":3691,"method":"getblock","params":["0000000000000000097067a6a27b5bbf5b06f3720c0a469860682f5e988f897f",false]},{"id":3691,"method":"getblock","params":["00000000000000000981fa4b7359e4b259febd90778d7c39a9f89213f10626a6",false]},{"id":3691,"method":"getblock","params":["000000000000000004de447ed62fa4bb57f81c7f759a25bbf6236ab28b474c74",false]},{"id":3691,"method":"getblock","params":["00000000000000000528e7d0e6be716e1a70df3e062cfdf34849f370e2ce0ae2",false]},{"id":3691,"method":"getblock","params":["000000000000000012159b8fc6f48e40e34a38785e9677f9a4c556376da73e54",false]},{"id":3691,"method":"getblock","params":["0000000000000000073828950152f727d935cb39f8002c4fb4d33abd9c0bac0b",false]},{"id":3691,"method":"getblock","params":["000000000000000011dc5bac011ed97469f10a14920c0c94feb424683877d29c",false]},{"id":3691,"method":"getblock","params":["000000000000000012114657c3228b10b68cec2803b3baf6264a8ffdb0864499",false]},{"id":3691,"method":"getblock","params":["00000000000000000e8464730266ddd933893b734bd81fc32f758424e079281e",false]},{"id":3691,"method":"getblock","params":["000000000000000000180d11161f9a544507cdf061aae69789fe4daa6766928b",false]},{"id":3691,"method":"getblock","params":["0000000000000000148852d029db387930b69134c12390b254acce2a3c96a81a",false]},{"id":3691,"method":"getblock","params":["000000000000000003e570dfc9eb9c233dac56e41f87e910e4a1da4c3856daf7",false]},{"id":3691,"method":"getblock","params":["0000000000000000078855ad3db1ba102e519a6936ddc0f4705df931a1b6b3a5",false]},{"id":3691,"method":"getblock","params":["00000000000000000cbde6e65fddfb60eee098c1e2fbe22c8411781ea096562b",false]},{"id":3691,"method":"getblock","params":["00000000000000000f0458022ec46ef3e8ecb513f96ce928a0d7e678af7f2789",false]},{"id":3691,"method":"getblock","params":["000000000000000001b9d754f177462d3fc2f6e4c02ed0cf708bc06ef27ddec9",false]},{"id":3691,"method":"getblock","params":["00000000000000001066ae66804e38cfdd0ed747ac8644078767112a7e5f11c2",false]},{"id":3691,"method":"getblock","params":["000000000000000008ed79ca2a57db5c5e1231ac229c6cedfdc1c9669abd9a38",false]},{"id":3691,"method":"getblock","params":["00000000000000000de737a9fad8910554a34544b8760f8a05c18f3fcacdfb23",false]},{"id":3691,"method":"getblock","params":["00000000000000000489858a72857ad8b9d23b3c2ab57c1e8cd77bcacf099497",false]},{"id":3691,"method":"getblock","params":["00000000000000000b5284e2cf94acace4d05376483c8e3eef335975ebf7c164",false]},{"id":3691,"method":"getblock","params":["0000000000000000125e8cb9a7150b9d93983844b7dc5bf938e040463ea7b83c",false]},{"id":3691,"method":"getblock","params":["000000000000000013d00b14327e51b0c6be96007f7194887c466163e3aee602",false]},{"id":3691,"method":"getblock","params":["0000000000000000103334791db1237717856d3304c7b6224b5afa850c8a658e",false]},{"id":3691,"method":"getblock","params":["000000000000000013e295ddfaacc53def0ab6e851c7cf45bea8f702392638f5",false]},{"id":3691,"method":"getblock","params":["000000000000000008dc35714506e3acbf363787a42b27f3269ff686bf56b060",false]},{"id":3691,"method":"getblock","params":["00000000000000000572471fe47b245024c390d27757ad8d3a566e7cc2794f78",false]},{"id":3691,"method":"getblock","params":["000000000000000002e062045aac66cb57b0ad6007bcf338f4ab722033f9f1c1",false]},{"id":3691,"method":"getblock","params":["000000000000000010c96ff2f9ea8b7ba16bb7319ed30908f4096f47cd96a8a5",false]},{"id":3691,"method":"getblock","params":["00000000000000000bb70c518539844d0b35b30c2c785413881c0de37eb00d38",false]},{"id":3691,"method":"getblock","params":["00000000000000001265655c91a28563d04779bd12c2bc4b06b92041acd569e1",false]},{"id":3691,"method":"getblock","params":["00000000000000000991bf0bb401cc78a4a7cf45a679b2e6b6ec8b4ba006ff88",false]},{"id":3691,"method":"getblock","params":["00000000000000000fdf11e92061c7833abaa85c1935dbca4ffc2cd19c9a97a0",false]},{"id":3691,"method":"getblock","params":["00000000000000000e391fa3d33f18cb650870ced7e7995e6049f315982557be",false]},{"id":3691,"method":"getblock","params":["000000000000000002dffd55c0569396bf95d6d97a5910d2d763649fa0fa6332",false]},{"id":3691,"method":"getblock","params":["00000000000000000d229442b868116039f6e3e3e23c06cd4bddd4cc2bdc189a",false]},{"id":3691,"method":"getblock","params":["00000000000000000f82577dba8208bc12a57b775e7e80630a3758235bcbf233",false]},{"id":3691,"method":"getblock","params":["000000000000000013aafe62cf1619b346bdce70857cfc4a5e290720fa7792b0",false]},{"id":3691,"method":"getblock","params":["00000000000000000aace1053b8012dd7ac7a29feffebff1c61e56bc64a75cce",false]},{"id":3691,"method":"getblock","params":["000000000000000006270f929c38962210da4d3acffed7d647204dbd107db6a3",false]},{"id":3691,"method":"getblock","params":["0000000000000000072981c31ffb2a9b2fe0042cba1ba38bacfc3e2c10e60d33",false]},{"id":3691,"method":"getblock","params":["000000000000000009e1fd054a0bf1c4ac3c66e98f3f40111c6412d6045f3108",false]},{"id":3691,"method":"getblock","params":["000000000000000009c1f4da23cf10dc377df38e890cfd70c6d136b848c41f8b",false]},{"id":3691,"method":"getblock","params":["00000000000000000ca11ce6b91503f33805cf1ee3b4093968b9b4b54462eee8",false]},{"id":3691,"method":"getblock","params":["000000000000000008a5494de1ca5f7c440b98d06d0f1cfb0e31d1a1ea522599",false]},{"id":3691,"method":"getblock","params":["00000000000000000cea9b85cb3d54649870e829d8da0b39ed83d0b425dee122",false]},{"id":3691,"method":"getblock","params":["00000000000000000c9ba89dbb3dfe60f04f88e3009567518ce712fd41d4fbc1",false]},{"id":3691,"method":"getblock","params":["0000000000000000008871e5489787ff3d34521fbb34139b123205c89934a077",false]},{"id":3691,"method":"getblock","params":["00000000000000000e8286e23a78a77489be9b42cc0736f34724f14eeae51cce",false]},{"id":3691,"method":"getblock","params":["00000000000000000f76114ff9272a83eb942255a8db1f4cd12db8c0f73dedcc",false]},{"id":3691,"method":"getblock","params":["000000000000000007ff802f8a338c5ea49689b9873de72655cfaa98c16dd56c",false]},{"id":3691,"method":"getblock","params":["000000000000000008dd6ccc0841004f6ad6c2370c1a21a91256ad4bf2abdfc5",false]},{"id":3691,"method":"getblock","params":["00000000000000000ff36b0d92e4ac331ec38789c732d1414f5b56891df50b30",false]},{"id":3691,"method":"getblock","params":["000000000000000010ef41e2a8a64ffa5b1493b343290d94ad72bcafb0af1a43",false]},{"id":3691,"method":"getblock","params":["00000000000000000afb3c47efee3580efe976fa1d616b7359d09b91dac1adca",false]},{"id":3691,"method":"getblock","params":["00000000000000000dc2bdcc3eb7f76cfc40d813c079659697c9cfc3347314fb",false]},{"id":3691,"method":"getblock","params":["000000000000000008680c32315e2275b3f3df727008fec61413d78ae2892e28",false]},{"id":3691,"method":"getblock","params":["00000000000000000235e23cbe5b6057d647150ae5bb78cc13a0cde52885c3e7",false]},{"id":3691,"method":"getblock","params":["000000000000000011098ba575fe764410854296bb935d4eb674f5271108c2eb",false]},{"id":3691,"method":"getblock","params":["00000000000000000c464471cdb1397bc35e1adda213ff27e6d3e7e5385dd47a",false]},{"id":3691,"method":"getblock","params":["00000000000000000db1ca6a42a335cad2ce377f90e59d0029656f2bfb2700f8",false]},{"id":3691,"method":"getblock","params":["0000000000000000061dce367344dde81c8631c8829ddcd9f0188a1bf4c99abd",false]},{"id":3691,"method":"getblock","params":["0000000000000000028478d602594138710044f7be0be17857de59ea67f395e1",false]},{"id":3691,"method":"getblock","params":["00000000000000000a0944d20980d166ee6c603dbce129ccf7e57980c3ce84fb",false]},{"id":3691,"method":"getblock","params":["000000000000000011d51ed321fac78a13760d83a6266d9f7aebf89596907f96",false]},{"id":3691,"method":"getblock","params":["00000000000000000ed30179725f30ea162a6d8a8df4ca9ef933deebb8ffb880",false]},{"id":3691,"method":"getblock","params":["00000000000000000d733dff6007fcf470059c4ada0e3fc25f90c60de85808f2",false]},{"id":3691,"method":"getblock","params":["000000000000000009e5779b03293fcb506355a05c97a9fff01734c13d6df30d",false]},{"id":3691,"method":"getblock","params":["000000000000000003e065659d59c1b861514cc4ef90ef43f47926cdf4b0300c",false]},{"id":3691,"method":"getblock","params":["00000000000000000c25a000c7f08acec1c626b5f66d1baa940db24ee9642aef",false]},{"id":3691,"method":"getblock","params":["000000000000000006b73a8933f93c000f1fb213268253cec51912aca3e3f808",false]},{"id":3691,"method":"getblock","params":["0000000000000000007ef279b1d6b408abc68cd38004e7d1f00656c8a631f6ae",false]},{"id":3691,"method":"getblock","params":["0000000000000000149a447a273d92da41f8a9c8d3771a65aceadb26d60e7478",false]},{"id":3691,"method":"getblock","params":["000000000000000014a22d9ca20f6eda91c42103b08cab6587d33a8bc03dbc77",false]},{"id":3691,"method":"getblock","params":["000000000000000005297676d57a701cf1ae0b25cae71db9535362484bbefaa1",false]},{"id":3691,"method":"getblock","params":["000000000000000013b344fb3a0db40d4a254583a3531cbd6857e78f74016893",false]},{"id":3691,"method":"getblock","params":["000000000000000014ad50b18a2affa406fb43ac63e02e9a5fc800e9803aca7e",false]},{"id":3691,"method":"getblock","params":["00000000000000001372b5beca6d9f187fb343292ab4233c53c22938344a03f9",false]},{"id":3691,"method":"getblock","params":["000000000000000010d5df197625cccfa8a38ed28b4a817b0eda40331b5cea38",false]},{"id":3691,"method":"getblock","params":["00000000000000000a4040d64cbab038dc27d06933fb29d4809aa577b174db34",false]},{"id":3691,"method":"getblock","params":["00000000000000000941aebb59ad568ab15ed3a5b2aef1e53c81290e328126c5",false]},{"id":3691,"method":"getblock","params":["000000000000000012eadb71770479e0906b54de84e7eb094ae2d1c8902d0b7b",false]},{"id":3691,"method":"getblock","params":["000000000000000010a47216ef7548792f212bdc30a986f29f8aef97425798da",false]},{"id":3691,"method":"getblock","params":["00000000000000000d9c2cb9cfda93430751f9bc2160d4ecad4da9ffe7b6bb20",false]},{"id":3691,"method":"getblock","params":["00000000000000000c5514ec784db2a05c50b5181aac08fc8fc24e5e57f2c26d",false]},{"id":3691,"method":"getblock","params":["000000000000000009e9976d45ec375ad5590e44fb7af4c9e491806467e0f6a5",false]},{"id":3691,"method":"getblock","params":["0000000000000000134ed919eb6d2d2ff618e62d5e09077cd0cedcfef9e28cba",false]},{"id":3691,"method":"getblock","params":["00000000000000000fbddaf74e065e7142bfc93eb327eaaf2f495998254355ea",false]},{"id":3691,"method":"getblock","params":["000000000000000014e2fff2e42ea07056c1c6ada9eb4124c9a4c718513c0a12",false]}]
Caused by: invalid JSON
Caused by: EOF while parsing a string at line 1 column 141852557
stack backtrace:
   0:   0x613e77 - backtrace::backtrace::trace::h1958117cdb5a1d48
   1:   0x61350f - backtrace::capture::Backtrace::new_unresolved::hc3290a5be7a3f6be
   2:   0x612dbb - error_chain::backtrace::imp::InternalBacktrace::new::h6a37c9ca19557917
   3:   0x5544bb - error_chain::State::new::h455971fddf457299
   4:   0x6031d7 - <core::result::Result<T, E> as electrs::errors::ResultExt<T>>::chain_err::he8c3d7d7b1799679
   5:   0x5e3b57 - electrs::daemon::Daemon::retry_call_jsonrpc::h6a27f00244deaaed
   6:   0x5e493f - electrs::daemon::Daemon::requests::h0a0fda5dc812e814
   7:   0x5e5c67 - electrs::daemon::Daemon::getblocks::h214d7fcea3e11b55
   8:   0x5be5c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65fd4fbd143d333c
   9:   0x5429a7 - std::panicking::try::do_call::h61c6c58d68c7ca3a
  10:   0x94dddf - __rust_maybe_catch_panic
                at libpanic_unwind/lib.rs:105
  11:   0x5ddd8f - <F as alloc::boxed::FnBox<A>>::call_box::h1a1e452abadf7cfa
  12:   0x943acb - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output=R> + 'a> as core::ops::function::FnOnce<A>>::call_once::he730338ad259b793
                at /checkout/src/liballoc/boxed.rs:650
                 - std::sys_common::thread::start_thread::ha977928eb5bc99e8
                at libstd/sys_common/thread.rs:24
  13:   0x932aeb - std::sys::unix::thread::Thread::new::thread_start::h70dac9a9680028d2
                at libstd/sys/unix/thread.rs:90
```

**Comment by romanz** [comment]
This probably happened due to a TCP disconnection during an active RPC...

**Comment by romanz** [comment]
I suggest restarting the indexing to see if/when it fails again.

**Comment by romanz** [comment]
@duckartes It seems that you are running an older version of `electrs`, since `retry_call_jsonrpc()` function was removed at https://github.com/romanz/electrs/commit/fc8656f7a40f4d37388b6ae54c7d62a0f1d62737#diff-de7d1c5164a16c3b86e59069620d7ec7L373.
Could you please try to run the latest version?

**Comment by duckartes** [comment]
What's the easiest way to manage building in the same pull directory? 

With Bitcoin I just make clean and pull the newest. 

Is there another way? Should it not be done this way?

Just deleted my romanz/electrs directory and database directory. 

Starting fresh with a ./run.sh

**Comment by romanz** [comment]
> With Bitcoin I just make clean and pull the newest.

IIUC, you should do be able to do the same with `electrs`.

> Just deleted my romanz/electrs directory and database directory.

I am trying to keep the DB format without too many incompatible changes, so you should be able to re-use the same database directory.

**Comment by duckartes** [comment]
Right on. 

I always like to start out fresh so I can see if it's acting the same, or if it fails at different parts from the beginning :)

**Comment by duckartes** [comment]
Everything started from scratch. Fresh pull and build. 

clang --version
clang version 3.8.1-24+rpi1 (tags/RELEASE_381/final)
Target: armv6--linux-gnueabihf
Thread model: posix

rustc --version
rustc 1.28.0 (9634041f0 2018-07-30)

```
2018-09-01T16:34:37.447-04:00 - INFO - best=0000000000000000001987a49d6c6a0a87c28fe46af4ca5fed9b85c6caee7dfb height=539538 @ 2018-09-01T20:30:41Z (539539 left to index)
2018-09-01T20:59:35.690-04:00 - WARN - reconnecting to bitcoind: disconnected from daemon while receiving
2018-09-01T20:59:45.116-04:00 - TRACE - closing DB at "/mnt/storage/.pin0de/electrs/mainnet"
2018-09-01T20:59:59.328-04:00 - ERROR - server failed: Error: invalid JSON
Caused by: EOF while parsing a string at line 1 column 142065549
stack backtrace:
   0:   0x601a7f - backtrace::backtrace::trace::h395a7b70198001d2
   1:   0x601117 - backtrace::capture::Backtrace::new_unresolved::h3197067c6f3673f7
   2:   0x6009c3 - error_chain::backtrace::imp::InternalBacktrace::new::ha1773bdae76d3aab
   3:   0x575d8f - error_chain::State::new::h6be3d9ef5556fad2
   4:   0x54383b - <core::result::Result<T, E> as electrs::errors::ResultExt<T>>::chain_err::h322413db25a3b792
   5:   0x5e8f0f - electrs::daemon::Daemon::retry_request_batch::h167f8ff67dab2765
   6:   0x5eba6f - electrs::daemon::Daemon::getblocks::h2159c8afae0413ac
   7:   0x5b62c7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h55a95ad3fd247eae
   8:   0x5e371f - std::panicking::try::do_call::h77bcd185d12eb079
   9:   0x93c58f - __rust_maybe_catch_panic
                at libpanic_unwind/lib.rs:105
  10:   0x5d0b9b - <F as alloc::boxed::FnBox<A>>::call_box::hd637e175b94ba293
  11:   0x93227b - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output=R> + 'a> as core::ops::function::FnOnce<A>>::call_once::he730338ad259b793
                at /checkout/src/liballoc/boxed.rs:650
                 - std::sys_common::thread::start_thread::ha977928eb5bc99e8
                at libstd/sys_common/thread.rs:24
  12:   0x9212ef - std::sys::unix::thread::Thread::new::thread_start::h70dac9a9680028d2
                at libstd/sys/unix/thread.rs:90
```

**Comment by duckartes** [comment]
My run script:

```
#!/bin/bash
set -eu
trap 'kill $(jobs -p)' EXIT

DELAY=5
LOG=/mnt/storage/.pin0de/electrs/electrs.log
CARGO="cargo +stable"

tail -v -n0 -F "$LOG" &

export RUST_BACKTRACE=1
while :
do
        $CARGO fmt
        $CARGO check --release
#       $CARGO run --release -- --skip-bulk-import --db-dir=/mnt/storage/.pin0de/electrs/ $* 2>> "$LOG"
        $CARGO run --release -- --db-dir=/mnt/storage/.pin0de/electrs --skip-bulk-import -vvvv --timestamp $* 2>> "$LOG"

        echo "Restarting in $DELAY seconds..."
        sleep $DELAY
done
```

**Comment by romanz** [comment]
I'll fix the underlying issue by verifying that all the data is read from the socket -> #56

**Comment by romanz** [comment]
Please let me know if this issue (RocksDB compilation error) can be resolved.

**Comment by duckartes** [comment]
librocksdb-sys successfully compiles

**Comment by romanz** [comment]
Happened again at https://github.com/romanz/electrs/issues/59#issuecomment-424861338.

**Comment by romanz** [comment]
@duckartes is it possible to update the `clang` package to a more recent version?

**Comment by romanz** [comment]
On my machine `stdarg.h` can be found here:
```bash
$ locate stdarg.h
/usr/include/c++/7/tr1/stdarg.h
/usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h
/usr/lib/llvm-6.0/lib/clang/6.0.0/include/stdarg.h
```

**Comment by duckartes** [comment]
Looks likes this is an issue with multiple clang being installed on my machine.

Case of **PEBKAC** here.

**Comment by duckartes** [comment]
```
clang-4.0 --version
clang version 4.0.1-10+rpi1~bpo9+1 (tags/RELEASE_401/final)
Target: armv6-unknown-linux-gnueabihf
Thread model: posix
```
Compiled fine this time, no errors.

**Comment by romanz** [comment]
No worries :)
