### ISSUE TITLE
error: Could not compile `chrono`.

### ISSUE THREAD

**Issue by duckartes** [romanz/electrs#59]
./run.sh

```
Checking chrono v0.4.6
error: couldn't read "/home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.6/src/offset/local.rs": stream did not contain valid UTF-8
   --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.6/src/offset/mod.rs:414:5
    |
414 | mod local;
    |     ^^^^^

error: aborting due to previous error

error: Could not compile `chrono`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

rustc --version
`rustc 1.29.0 (aa3ca1994 2018-09-11)`

**Comment by romanz** [comment]
Took a look at the `chrono` build issue - it seems to build correctly on my machine:
```
✓ 11:54:02 /tmp 
$ git clone https://github.com/chronotope/chrono
Cloning into 'chrono'...
remote: Enumerating objects: 8497, done.
remote: Total 8497 (delta 0), reused 0 (delta 0), pack-reused 8497
Receiving objects: 100% (8497/8497), 3.30 MiB | 341.00 KiB/s, done.
Resolving deltas: 100% (7247/7247), done.
✓ 11:54:16 /tmp 
$ cd chrono/
✓ 11:54:20 /tmp/chrono [master] 
$ cargo build
    Updating crates.io index
   Compiling num-traits v0.2.6                                                                                                                                                                                                                                                  
   Compiling num-integer v0.1.39                                                                                                                                                                                                                                                
   Compiling libc v0.2.43                                                                                                                                                                                                                                                       
   Compiling time v0.1.40                                                                                                                                                                                                                                                       
   Compiling chrono v0.4.6 (/tmp/chrono)                                                                                                                                                                                                                                        
    Finished dev [unoptimized + debuginfo] target(s) in 22.54s                                                                                                                                                                                                                  
✓ 11:54:53 /tmp/chrono [master] 
```
Could you please attach the source file in question?
```
$ sha256sum ~/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.6/src/offset/mod.rs 
2aeeb0fa4c657e810f78ff239d7c52f07c33a2b7bdfc8b3765f4339dcafa0088  /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.6/src/offset/mod.rs
✓ 12:00:46 /tmp/chrono [master] 
$ sha256sum src/offset/mod.rs 
2aeeb0fa4c657e810f78ff239d7c52f07c33a2b7bdfc8b3765f4339dcafa0088  src/offset/mod.rs
✓ 12:00:57 /tmp/chrono [master] 
```

**Comment by duckartes** [comment]
Forgive the delay, but it's stalling at librocksdb-sys currently. 
```

./run2.sh
==> /mnt/storage/.pin0de/electrs/electrs.log <==
   Compiling librocksdb-sys v5.14.2
error: failed to run custom build command for `librocksdb-sys v5.14.2`
process didn't exit successfully: `/mnt/storage/.pin0de/src/github.com/romanz/electrs/target/release/build/librocksdb-sys-cbe23b8629ebf6ff/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/

--- stderr
rocksdb/include/rocksdb/c.h:48:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
rocksdb/include/rocksdb/c.h:68:10: fatal error: 'stdarg.h' file not found
rocksdb/include/rocksdb/c.h:48:9: warning: #pragma once in main file [-Wpragma-once-outside-header], err: false
rocksdb/include/rocksdb/c.h:68:10: fatal error: 'stdarg.h' file not found, err: true
thread 'main' panicked at 'unable to generate rocksdb bindings: ()', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main

```

**Comment by romanz** [comment]
Seems similar to #55, let's move the discussion there.

**Comment by romanz** [comment]
Can this issue be marked as resolved?
