### ISSUE TITLE
Panicked rpc, peer and acceptor threads

### ISSUE THREAD

**Issue by devrandom** [romanz/electrs#80]
The log entries below are emitted, and the RPC port closes.  A restart is required to recover.

```
2018-10-29T12:24:44.239+00:00 - INFO - [10.52.2.1:54432] connected peer
thread 'peer' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'rpc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5
thread 'acceptor' panicked at 'send failed: "SendError(..)"', libcore/result.rs:945:5
```

**Comment by romanz** [comment]
Thanks for reporting this issue!

Could you please reproduce this issue with `export RUST_BACKTRACE=1` set?
Also, in which scenario does this issue happen?

**Comment by devrandom** [comment]
It's not clear what is the specific scenario, nothing special was happening.  Added the backtrace env var and will let you know if it happens again.

**Comment by devrandom** [comment]
That's already the case.

**Comment by devrandom** [comment]
It happened again, here is a stacktrace:

```
2018-11-05T13:20:11.521+00:00 - TRACE - RPC Done
2018-11-05T13:20:11.521+00:00 - DEBUG - [10.52.11.1:53392] shutting down connection
2018-11-05T13:20:11.521+00:00 - INFO - [10.52.11.1:53392] disconnected peer
2018-11-05T13:20:21.521+00:00 - INFO - [10.52.11.1:53472] connected peer
2018-11-05T13:20:21.522+00:00 - TRACE - RPC Done
2018-11-05T13:20:21.522+00:00 - DEBUG - [10.52.11.1:53472] shutting down connection
2018-11-05T13:20:21.522+00:00 - INFO - [10.52.11.1:53472] disconnected peer
2018-11-05T13:20:31.524+00:00 - INFO - [10.52.11.1:53548] connected peer
thread 'peer' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: electrs::util::spawn_thread
  10: electrs::rpc::Connection::run
thread 'rpc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: electrs::util::spawn_thread
thread 'acceptor' panicked at 'send failed: "SendError(..)"', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: electrs::rpc::RPC::start_acceptor::{{closure}}
2018-11-05T13:30:29.019+00:00 - DEBUG - downloading new block headers (548861 already indexed) from 000000000000000000099ab1313fc5cd5c74f6dc99714714fbb3e8d84c77fa7d
2018-11-05T13:30:29.020+00:00 - TRACE - downloaded 1 block headers
2018-11-05T13:30:29.020+00:00 - INFO - best=000000000000000000099ab1313fc5cd5c74f6dc99714714fbb3e8d84c77fa7d height=548861 @ 2018-11-05T13:29:56Z (1 left to index)
2018-11-05T13:30:29.142+00:00 - DEBUG - applying 1 new headers from height 548861
2018-11-05T13:37:20.168+00:00 - DEBUG - downloading new block headers (548862 already indexed) from 0000000000000000001de500f5bb3a0775e9ac0e8e2f56f0947abd835d4e4d11
2018-11-05T13:37:20.169+00:00 - TRACE - downloaded 1 block headers
2018-11-05T13:37:20.169+00:00 - INFO - best=0000000000000000001de500f5bb3a0775e9ac0e8e2f56f0947abd835d4e4d11 height=548862 @ 2018-11-05T13:36:46Z (1 left to index)
2018-11-05T13:37:20.397+00:00 - DEBUG - applying 1 new headers from height 548862
2018-11-05T13:38:58.503+00:00 - DEBUG - downloading new block headers (548863 already indexed) from 000000000000000000212cf4307fb213765d27ed2e26948dc3fd3e50df9fb5d4
2018-11-05T13:38:58.504+00:00 - TRACE - downloaded 1 block headers
2018-11-05T13:38:58.504+00:00 - INFO - best=000000000000000000212cf4307fb213765d27ed2e26948dc3fd3e50df9fb5d4 height=548863 @ 2018-11-05T13:38:48Z (1 left to index)
2018-11-05T13:38:58.647+00:00 - DEBUG - applying 1 new headers from height 548863
2018-11-05T13:47:31.238+00:00 - DEBUG - downloading new block headers (548864 already indexed) from 000000000000000000225b187c04074bcc320376ecd9af64a448a5cf03406187
2018-11-05T13:47:31.239+00:00 - TRACE - downloaded 1 block headers
2018-11-05T13:47:31.239+00:00 - INFO - best=000000000000000000225b187c04074bcc320376ecd9af64a448a5cf03406187 height=548864 @ 2018-11-05T13:47:14Z (1 left to index)
2018-11-05T13:47:31.420+00:00 - DEBUG - applying 1 new headers from height 548864
2018-11-05T13:48:48.622+00:00 - DEBUG - downloading new block headers (548865 already indexed) from 0000000000000000000e163c9b5c4a3b11b65b3d0fe43bb6060eb31f65e81e29
2018-11-05T13:48:48.622+00:00 - TRACE - downloaded 1 block headers
```

**Comment by romanz** [comment]
Sorry for the delayed response... 
It seems that something went wrong while sending data from electrs to Electrum, but I am still not sure where/why the actual error happens (i.e. where the offending `unwrap()` takes place).
Could you please try to reproduce it with `RUST_BACKTRACE=full`?

**Comment by devrandom** [comment]
Will follow up once it happens again.

**Comment by devrandom** [comment]
Just got the issue again, but I'm not sure there's much more info with `=full`:

```
thread 'peer' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5
stack backtrace:
   0:     0x555909c2ab8e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h4e8f20df13e312d1
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x555909c1c636 - std::sys_common::backtrace::print::ha948e198817dc736
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x555909c18e7d - std::panicking::default_hook::{{closure}}::hbce70b8b8e9560c0
                               at libstd/panicking.rs:211
   3:     0x555909c18bf0 - std::panicking::default_hook::h445b4bc93ff2c15f
                               at libstd/panicking.rs:227
   4:     0x555909c1952c - std::panicking::rust_panic_with_hook::h542dacac3f3a20d8
                               at libstd/panicking.rs:475
   5:     0x555909c190e9 - std::panicking::continue_panic_fmt::hd989cd729c0c5a4b
                               at libstd/panicking.rs:390
   6:     0x555909c18fe5 - rust_begin_unwind
                               at libstd/panicking.rs:325
   7:     0x555909c7087b - core::panicking::panic_fmt::h26b7cf0675909ac6
                               at libcore/panicking.rs:77
   8:     0x5559098585b8 - core::result::unwrap_failed::h5c65c5f2ca61b595
   9:     0x55590989102e - electrs::util::spawn_thread::h1945ec226d478c45
  10:     0x55590981eebb - electrs::rpc::Connection::run::h844468b943c4f2f9
  11:     0x5559098733de - std::sys_common::backtrace::__rust_begin_short_backtrace::h8a755b3fef837c3f
  12:     0x55590989446d - std::panicking::try::do_call::h2e708c2ba139285e
  13:     0x555909c39889 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  14:     0x555909898dd9 - <F as alloc::boxed::FnBox<A>>::call_box::h780f7321702128ed
  15:     0x555909c1b33a - std::sys_common::thread::start_thread::h24226b876494ff77
                               at /checkout/src/liballoc/boxed.rs:652
                               at libstd/sys_common/thread.rs:24
  16:     0x555909c19a95 - std::sys::unix::thread::Thread::new::thread_start::h0aab6afcd022cdd8
                               at libstd/sys/unix/thread.rs:90
  17:     0x7f6f70e1b493 - start_thread
  18:     0x7f6f70946ace - __clone
  19:                0x0 - <unknown>
thread 'rpc' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5
stack backtrace:
   0:     0x555909c2ab8e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h4e8f20df13e312d1
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x555909c1c636 - std::sys_common::backtrace::print::ha948e198817dc736
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x555909c18e7d - std::panicking::default_hook::{{closure}}::hbce70b8b8e9560c0
                               at libstd/panicking.rs:211
   3:     0x555909c18bf0 - std::panicking::default_hook::h445b4bc93ff2c15f
                               at libstd/panicking.rs:227
   4:     0x555909c1952c - std::panicking::rust_panic_with_hook::h542dacac3f3a20d8
                               at libstd/panicking.rs:475
   5:     0x555909c190e9 - std::panicking::continue_panic_fmt::hd989cd729c0c5a4b
                               at libstd/panicking.rs:390
   6:     0x555909c18fe5 - rust_begin_unwind
                               at libstd/panicking.rs:325
   7:     0x555909c7087b - core::panicking::panic_fmt::h26b7cf0675909ac6
                               at libcore/panicking.rs:77
   8:     0x5559098585b8 - core::result::unwrap_failed::h5c65c5f2ca61b595
   9:     0x555909890f21 - electrs::util::spawn_thread::h15c41228de743039
  10:     0x555909873831 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha49a1637c83e6648
  11:     0x5559098946d6 - std::panicking::try::do_call::hd00d3a3fe0ab79b2
  12:     0x555909c39889 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  13:     0x555909899892 - <F as alloc::boxed::FnBox<A>>::call_box::hea456478a44dc0a2
  14:     0x555909c1b33a - std::sys_common::thread::start_thread::h24226b876494ff77
                               at /checkout/src/liballoc/boxed.rs:652
                               at libstd/sys_common/thread.rs:24
  15:     0x555909c19a95 - std::sys::unix::thread::Thread::new::thread_start::h0aab6afcd022cdd8
                               at libstd/sys/unix/thread.rs:90
  16:     0x7f6f70e1b493 - start_thread
  17:     0x7f6f70946ace - __clone
  18:                0x0 - <unknown>
thread 'acceptor' panicked at 'send failed: "SendError(..)"', libcore/result.rs:945:5
stack backtrace:
   0:     0x555909c2ab8e - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h4e8f20df13e312d1
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x555909c1c636 - std::sys_common::backtrace::print::ha948e198817dc736
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:     0x555909c18e7d - std::panicking::default_hook::{{closure}}::hbce70b8b8e9560c0
                               at libstd/panicking.rs:211
   3:     0x555909c18bf0 - std::panicking::default_hook::h445b4bc93ff2c15f
                               at libstd/panicking.rs:227
   4:     0x555909c1952c - std::panicking::rust_panic_with_hook::h542dacac3f3a20d8
                               at libstd/panicking.rs:475
   5:     0x555909c190e9 - std::panicking::continue_panic_fmt::hd989cd729c0c5a4b
                               at libstd/panicking.rs:390
   6:     0x555909c18fe5 - rust_begin_unwind
                               at libstd/panicking.rs:325
   7:     0x555909c7087b - core::panicking::panic_fmt::h26b7cf0675909ac6
                               at libcore/panicking.rs:77
   8:     0x555909858d68 - core::result::unwrap_failed::h977dad9f54e02a9c
   9:     0x555909882ff1 - electrs::rpc::RPC::start_acceptor::{{closure}}::h87f870bf255abee8
  10:     0x555909872b14 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5eefeb22ed83bece
  11:     0x5559098944f4 - std::panicking::try::do_call::h45247d01f5feea0a
  12:     0x555909c39889 - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:105
  13:     0x555909898600 - <F as alloc::boxed::FnBox<A>>::call_box::h2b9844eeb6e42fb1
  14:     0x555909c1b33a - std::sys_common::thread::start_thread::h24226b876494ff77
                               at /checkout/src/liballoc/boxed.rs:652
                               at libstd/sys_common/thread.rs:24
  15:     0x555909c19a95 - std::sys::unix::thread::Thread::new::thread_start::h0aab6afcd022cdd8
                               at libstd/sys/unix/thread.rs:90
  16:     0x7f6f70e1b493 - start_thread
  17:     0x7f6f70946ace - __clone
  18:                0x0 - <unknown>
```

**Comment by devrandom** [comment]
Note that we have a liveness check that opens a TCP connection to `electrs` but doesn't issue any commands.  I don't know if that's more likely to trigger the issue.

**Comment by romanz** [comment]
Following #93, could you try to see if https://github.com/romanz/electrs/commit/04af2448aea267d4dee3da30ccba8cd1e035b479 (from `nonblocking` branch) helps with the panic?

**Comment by devrandom** [comment]
I'm not able to test it right now, will probably wait for the next point release.
