### ISSUE TITLE
thread 'bulk_writer' panicked at 'indexing failed: Error(Msg("failed to index \"/home/user/.bitcoin/blocks/blk00003.dat\"")

### ISSUE THREAD

**Issue by s3ton** [romanz/electrs#88]
```
2018-11-13T15:23:38.892+01:00 - DEBUG - found 0 indexed blocks
2018-11-13T15:24:05.261+01:00 - DEBUG - applying 549929 new headers from height 0
2018-11-13T16:46:43.700+01:00 - DEBUG - no more blocks to index
2018-11-13T16:46:46.020+01:00 - DEBUG - no more blocks to index
thread 'bulk_writer' panicked at 'indexing failed: Error(Msg("failed to index \"/home/user/.bitcoin/blocks/blk00003.dat\""), State { next_error: Some(Error(Msg("failed to parse block at 83434250..83457009"), State { next_error: Some(OversizedVectorAllocation { requested: 3187813469848891317, max: 33554432 }), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0:     0x5557e9b8aeac - backtrace::backtrace::trace::h2ccbf42230f6479e
   1:     0x5557e9b89982 - backtrace::capture::Backtrace::new_unresolved::h272161fa325e29b5
   2:     0x5557e9b89267 - error_chain::backtrace::imp::InternalBacktrace::new::h4bd60e84b572b75b
   3:     0x5557e9ad7939 - error_chain::State::new::h904ce0497de2c41a
   4:     0x5557e9b2e46c - <core::result::Result<T, E> as electrs::errors::ResultExt<T>>::chain_err::h4edf4ed22fc7b86b
   5:     0x5557e9ab7acd - electrs::bulk::Parser::index_blkfile::hde333d6ea4c0a95d
   6:     0x5557e9b4b716 - std::sys_common::backtrace::__rust_begin_short_backtrace::h45eea6e33cee2548
   7:     0x5557e9aafbe4 - std::panicking::try::do_call::h0c8aa4716455c310
   8:     0x5557e9f0cf69 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
   9:     0x5557e9b56b9e - <F as alloc::boxed::FnBox<A>>::call_box::h0091068ce4ccf8f8
  10:     0x5557e9eff90a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hfedf8d10954bca7a
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::h75d887c7d2cc4479
                        at libstd/sys_common/thread.rs:24
  11:     0x5557e9eee485 - std::sys::unix::thread::Thread::new::thread_start::h8414caee632bf9ed
                        at libstd/sys/unix/thread.rs:90
  12:     0x7f8ed62bd6b9 - start_thread
  13:     0x7f8ed5ddd41c - clone
  14:                0x0 - <unknown>) } })), backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0:     0x5557e9b8aeac - backtrace::backtrace::trace::h2ccbf42230f6479e
   1:     0x5557e9b89982 - backtrace::capture::Backtrace::new_unresolved::h272161fa325e29b5
   2:     0x5557e9b89267 - error_chain::backtrace::imp::InternalBacktrace::new::h4bd60e84b572b75b
   3:     0x5557e9ad7939 - error_chain::State::new::h904ce0497de2c41a
   4:     0x5557e9b2e46c - <core::result::Result<T, E> as electrs::errors::ResultExt<T>>::chain_err::h4edf4ed22fc7b86b
   5:     0x5557e9ab7acd - electrs::bulk::Parser::index_blkfile::hde333d6ea4c0a95d
   6:     0x5557e9b4b716 - std::sys_common::backtrace::__rust_begin_short_backtrace::h45eea6e33cee2548
   7:     0x5557e9aafbe4 - std::panicking::try::do_call::h0c8aa4716455c310
   8:     0x5557e9f0cf69 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
   9:     0x5557e9b56b9e - <F as alloc::boxed::FnBox<A>>::call_box::h0091068ce4ccf8f8
  10:     0x5557e9eff90a - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::hfedf8d10954bca7a
                        at liballoc/boxed.rs:656
                         - std::sys_common::thread::start_thread::h75d887c7d2cc4479
                        at libstd/sys_common/thread.rs:24
  11:     0x5557e9eee485 - std::sys::unix::thread::Thread::new::thread_start::h8414caee632bf9ed
                        at libstd/sys/unix/thread.rs:90
  12:     0x7f8ed62bd6b9 - start_thread
  13:     0x7f8ed5ddd41c - clone
  14:                0x0 - <unknown>) } })', libcore/result.rs:1009:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
thread 'main' panicked at 'writer panicked: Any', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: electrs::bulk::index_blk_files
  10: electrs::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start
```
What should I do?
For reference I'm running electrs on a 4gb ram machine and saving the db to an hdd.
Thanks for the help and for your work

**Comment by s3ton** [comment]
Hey thanks for the answer.
Here is the file: https://we.tl/t-VqybvgTe3A

**Comment by romanz** [comment]
Got it, thanks!
```
7bbb1fedef011574f4016bb41382422d3d01cea5914fca1ddca3749e956e7c80  bugs/blk00003.dat
```

**Comment by erikarvstedt** [comment]
Same here:
```
thread 'bulk_writer' panicked at 'indexing failed:
Error(Msg("failed to index \"/data/bitcoin/blocks/blk00246.dat\""),
         State { next_error: Some(Error(Msg("failed to parse block at 92741111..93639467"),
                 State { next_error: Some(OversizedVectorAllocation { requested: 397541376511, max: 33554432 }),
                 backtrace: InternalBacktrace { backtrace: None } })),
         backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:1009:5
```
The offending block:
`blk00246.dat` (https://we.tl/t-zvkMcdG3M9)
sha256: `89b1f65c8fa390f93858cf79662cce04d532d009634b1268ee657a87ca85a8ef`

Would really love to get this fixed, it's a total blocker.

**Comment by romanz** [comment]
Thanks for the report and sorry for the unresponsiveness...
Will take a look at this issue during the weekend.

**Comment by erikarvstedt** [comment]
Thanks! Do you have any insights in what could have caused `blk00246.dat` to be invalid? Bitcoin Core? Storage defects?

**Comment by romanz** [comment]
Actually, I am not sure...
bitcoind prefixes each block stored on disk with a "magic" 4-byte value ([link](https://bitcoin.org/en/developer-reference#term-start-string)) and I am using it to split the blocks from the blk*.dat file.
It is possible that there is a small chance that this "magic" value have appeared in the blk*.dat file without being followed block.
I have added a few more debugging log statements ([commit](https://github.com/romanz/electrs/commit/7456831b92831358d7e72a0458332a2f33a2faf5)), and it seem that this is the case for this issue (the parser "resyncs" after a few bytes).

**Comment by romanz** [comment]
Please re-open if the issue persists.

**Comment by jamesob** [comment]
Also seeing this:
```
electrs_1   | 2019-08-02T15:47:30.091+00:00 - DEBUG - no more blocks to index
electrs_1   | 2019-08-02T15:47:30.382+00:00 - DEBUG - no more blocks to index
electrs_1   | thread 'bulk_writer' panicked at 'indexing failed: Error(Msg("failed to index \"/bitcoin_data/blocks/blk01251.dat\""), State { next_error: Some(Error(Msg("failed to parse block at 74419262..75547591"), State { next_error: Some(OversizedVectorAllocation { requested: 34181176215732223, max: 33554432 }), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:1009:5
electrs_1   | note: Run with `RUST_BACKTRACE=1` for a backtrace.
electrs_1   | thread 'main' panicked at 'writer panicked: Any', libcore/result.rs:1009:5
```

Block `blk01251.dat` uploaded here: https://ufile.io/iq2zjvnt

**Comment by jamesob** [comment]
This was resolved by switching to `master` - I had been running on the `v0.4.3` tag.
