### ISSUE TITLE
Bug: cannot finish DB compaction on macOS due to open file limit

### ISSUE THREAD

**Issue by torkelrogstad** [romanz/electrs#918]
**Describe the bug**
Block compaction panics due to too many files open. 

**Electrs version**
0.10.0, built from master. 

**To Reproduce**
1. Build from master a1460ec4a90e45c863c29f66932dd91a0aea9f6f with `cargo build --locked --release`
2. Run with `./target/release/electrs  --log-filters=DEBUG --skip-block-download-wait`
3. Wait until block compaction is reached 
4. Error: `thread 'main' panicked at 'DB::put failed: Error { message: "IO error: While open a file for random read: ./db/bitcoin/000213.sst: Too many open files" }', src/db.rs:342:14`

**Expected behavior**
I'd expect block compaction to finish

**Configuration**
I don't use a configuration file for this. 

Environment variables: `ELECTRS_X=Y;...`: none
Arguments: `--foo`: `--log-filters=DEBUG --skip-block-download-wait`

**System running electrs**
 - Deployment method: manual 
 - OS name and version (name of distribution and version in case of Linux): macOS Ventura 13.5

**Additional context**
I tried building this with Prometheus support in order to inspect the file descriptor progress, but got this result: 

```
❯ cargo build --locked --release --all-features
   Compiling electrs v0.10.0 (/Users/torkel/dev/rust/electrs)
error[E0432]: unresolved import `prometheus::process_collector`
 --> src/metrics.rs:6:21
  |
6 |     use prometheus::process_collector::ProcessCollector;
  |                     ^^^^^^^^^^^^^^^^^ could not find `process_collector` in `prometheus`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `electrs` due to previous error
```

`ulimit -n` reports 256, but I'm not sure if this is the correct number for max open files. 

Posting logs. 
<details>
❯ ./target/release/electrs  --log-filters=DEBUG --skip-block-download-wait
Starting electrs 0.10.0 on aarch64 macos with Config { network: Bitcoin, db_path: "./db/bitcoin", daemon_dir: "/Users/torkel/.bitcoin", daemon_auth: CookieFile("/Users/torkel/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: true, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.10.0 (Electrum Rust Server)!", signet_magic: f9beb4d9, args: [] }
[2023-08-15T13:22:58.544Z DEBUG tiny_http] Server listening on 127.0.0.1:4224
[2023-08-15T13:22:58.544Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2023-08-15T13:22:58.544Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:50001
[2023-08-15T13:22:58.544Z DEBUG tiny_http] Running accept thread
[2023-08-15T13:22:58.652Z INFO  electrs::db] "./db/bitcoin": 652 SST files, 59.91444729 GB, 5.297402539 Grows
[2023-08-15T13:22:58.652Z DEBUG electrs::db] DB Some(Config { compacted: false, format: 0 })
[2023-08-15T13:22:59.489Z INFO  electrs::chain] loading 803298 headers, tip=000000000000000000003b002ef7631e504a76fd0f46a4ed5905e6fa42b17701
[2023-08-15T13:23:00.601Z INFO  electrs::chain] chain updated: tip=000000000000000000003b002ef7631e504a76fd0f46a4ed5905e6fa42b17701, height=803298
[2023-08-15T13:23:00.603Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2023-08-15T13:23:00.603Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2023-08-15T13:23:00.604Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2023-08-15T13:23:00.604Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2023-08-15T13:23:00.604Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2023-08-15T13:23:00.604Z DEBUG electrs::p2p] peer version: VersionMessage { version: 70016, services: ServiceFlags(1033), timestamp: 1692105780, receiver: Address {services: ServiceFlags(NONE), address: 0.0.0.0, port: 0}, sender: Address {services: ServiceFlags(NETWORK|WITNESS|NETWORK_LIMITED), address: 0.0.0.0, port: 0}, nonce: 788258135769235039, user_agent: "/Satoshi:24.0.1/", start_height: 803302, relay: true }
[2023-08-15T13:23:00.605Z DEBUG electrs::p2p] got 4 new headers
[2023-08-15T13:23:00.605Z INFO  electrs::index] indexing 4 blocks: [803299..803302]
[2023-08-15T13:23:00.605Z DEBUG electrs::p2p] loading 4 blocks
[2023-08-15T13:23:00.751Z DEBUG electrs::index] writing 33610 funding and 27220 spending rows from 19149 transactions, 4 blocks
[2023-08-15T13:23:00.768Z INFO  electrs::chain] chain updated: tip=00000000000000000000f04941e8c2596a2986658dcc93077901b2a7f83a57b4, height=803302
[2023-08-15T13:23:00.768Z DEBUG electrs::p2p] got 0 new headers
[2023-08-15T13:23:00.784Z INFO  electrs::db] starting config compaction
[2023-08-15T13:23:00.785Z INFO  electrs::db] starting headers compaction
[2023-08-15T13:23:01.368Z INFO  electrs::db] starting txid compaction
car[2023-08-15T13:26:45.489Z DEBUG electrs::p2p] peer inventory: [Block(0x00000000000000000003e00fc88fd8fcd2fd0cdea5c96b66be51c259189e1af7)]
[2023-08-15T13:26:51.788Z INFO  electrs::db] starting funding compaction
[2023-08-15T13:26:52.094Z INFO  electrs::db] starting spending compaction
thread 'main' panicked at 'DB::put failed: Error { message: "IO error: While open a file for random read: ./db/bitcoin/000213.sst: Too many open files" }', src/db.rs:342:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-08-15T13:26:52.095Z INFO  electrs::db] closing DB at ./db/bitcoin
[2023-08-15T13:26:53.125Z DEBUG electrs::p2p] closing p2p_loop thread: no more requests to handle
[2023-08-15T13:26:53.125Z DEBUG electrs::p2p] closing p2p_send thread: no more messages to send
[2023-08-15T13:26:53.125Z DEBUG electrs::p2p] closing p2p_recv thread: connection closed
</details>

**Comment by torkelrogstad** [comment]
Managed to get around this by increasing the file limit with `ulimit -n LARGE_NUMBER`. However I've never had software crash on my machine before due to this. I think it would be reasonable for `electrs` to try and stay within the allotted limit.

**Comment by romanz** [comment]
Thanks for reporting this issue!
Will reproduce on a Linux machine to collect file descriptor usage metrics.

**Comment by romanz** [comment]
https://github.com/tikv/rust-prometheus/blob/6e81890773ef82e3bcc6c080d406543da1fb8073/src/process_collector.rs#L5

> **Additional context**
> I tried building this with Prometheus support in order to inspect the file descriptor progress, but got this result:

https://github.com/tikv/rust-prometheus/blob/6e81890773ef82e3bcc6c080d406543da1fb8073/src/process_collector.rs#L5 :(

**Comment by romanz** [comment]
According to Prometheus, electrs uses ~350 file descriptors during compaction:
![image](https://github.com/romanz/electrs/assets/9900/23332b51-479a-4a94-8e86-d0096926fde3)

**Comment by romanz** [comment]
> However I've never had software crash on my machine before due to this.

I assume that the reason behind this is that the initial sync process writes many SST files (containing the index) and then merges them during the full compaction. In order to merge them, RocksDB needs to open all of them - failing if there are more than 256 SST files to be merged. 
This issue is expected since the blockchain is growing, and so is the number of files to merge during the full compaction.
We'll probably need to update the docs to suggest increasing `ulimit -n` to a larger value (on my machine it is set to 1024).

**Comment by torkelrogstad** [comment]
Right, interesting, thanks! Probably a good idea to update the docs, if it isn't possible to get RocksDB to be stingier with the files. For reference, my `ulimit -n` is 256, which I believe is the default on macOS

**Comment by dzdidi** [comment]
same issue now on Ubuntu with `ulimit -n` being `1024`

**Comment by romanz** [comment]
@dzdidi Could you please share the logs?

**Comment by dzdidi** [comment]
@romanz , sure, also I'm running blockstream's fork, applogies if this is relevant only to the fork.

Note this is during initial sync against fully synced bitcoind.

these are the logs from the restart attempt:
```
Oct 16 07:19:57 ***** electrs[1357423]: Config { log: StdErrLog { verbosity: Debug, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Never, show_module_names: false }, network_type: Bitcoin, db_path: "/mnt/disks/data/electrs/electrs_data/mainnet", daemon_dir: "/mnt/disks/data/bitcoin-data", blocks_dir: "/mnt/disks/data/bitcoin-data/block-data/blocks/", daemon_rpc_addr: 127.0.0.1:8332, daemon_parallelism: 4, cookie: Some("*******"), electrum_rpc_addr: 127.0.0.1:50001, http_addr: 127.0.0.1:8800, http_socket_file: None, monitoring_addr: 127.0.0.1:4224, jsonrpc_import: false, light_mode: false, address_search: false, index_unspendables: false, cors: None, precache_scripts: None, utxos_limit: 500, electrum_txs_limit: 500, electrum_banner: "Welcome to electrs-esplora 0.4.1", electrum_rpc_logging: None, initial_sync_compaction: false }
Oct 16 07:19:57 ***** electrs[1357423]: DEBUG Server listening on 127.0.0.1:4224
Oct 16 07:19:57 ***** electrs[1357423]: DEBUG Running accept thread
Oct 16 07:19:57 ***** electrs[1357423]: INFO NetworkInfo { version: 230000, subversion: "/Satoshi:23.0.0/", relayfee: 5e-6 }
Oct 16 07:19:57 ***** electrs[1357423]: INFO BlockchainInfo { chain: "main", blocks: 865868, headers: 865868, bestblockhash: "00000000000000000001b23708bcab58997448e40218d01608c2e7075fb12be7", pruned: false, verificationprogress: 0.9999961, initialblockdownload: Some(false) }
Oct 16 07:19:57 ***** electrs[1357423]: DEBUG opening DB at "/mnt/disks/data/electrs/electrs_data/mainnet/newindex/txstore"
Oct 16 07:19:59 ***** electrs[1357423]: thread 'main' panicked at src/new_index/db.rs:29:46:
Oct 16 07:19:59 ***** electrs[1357423]: valid iterator: Error { message: "IO error: While open a file for random read: /mnt/disks/data/electrs/electrs_data/mainnet/newindex/txstore/000310.sst: Too many open files" }
Oct 16 07:19:59 ***** electrs[1357423]: stack backtrace:
Oct 16 07:19:59 ***** electrs[1357423]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 16 07:19:59 ***** systemd[1]: electrs.service: Main process exited, code=dumped, status=6/ABRT

```

Note, I'm running it with `systemd` , adding `LimitNOFILE=4096` to `[SERVICE]` section of systemd service file seem to help, but I'm still not much above `1024`:
```
~$ ll /mnt/disks/data/electrs/electrs_data/mainnet/newindex/txstore/ | wc -l
> 1982
```

**Comment by romanz** [comment]
blockstream/electrs is using larger indices, so it requires increasing the default limits:
https://github.com/Blockstream/electrs/blob/new-index/src%2Fnew_index%2Fdb.rs#L88

**Comment by jharveyb** [comment]
Necrobumping, I hit this issue while testing current master / `9cd09afa229df89214f59816e5142f0f58ff6c48` on a Debian 13 box. However, I think this was because I set `db_parallelism` to 4 in the config.

Resetting it to 1, I still had a crash during compaction:

```bash
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: Starting electrs 0.11.1 on x86_64 linux with Config { network: Bitcoin, db_dir: "/home/goss/Electrs", db_log_dir: None, db_parallelism: 1, daemon_auth: CookieFile("/home/goss/Bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, skip_block_download_wait: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.11.1 (Electrum Rust Server)!" }
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.080Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.080Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:50001
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.080Z INFO  bindex::chain] index: Config { db_path: "/home/goss/Electrs/bitcoin", url: "http://127.0.0.1:8332" }
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.676Z INFO  bindex::db] CF config: 0 files, 0.000000 MBs
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.677Z INFO  bindex::db] CF headers: 871 files, 76.428536 MBs
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.679Z INFO  bindex::db] CF txpos: 963 files, 1418.284035 MBs
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.682Z INFO  bindex::db] CF txid: 970 files, 18608.318436 MBs
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.685Z INFO  bindex::db] CF script_hash: 970 files, 56502.443199 MBs
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.685Z INFO  bindex::db] CF spending: 0 files, 0.000000 MBs
Jul 29 14:30:09 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:09.685Z INFO  bindex::db] CF funding: 0 files, 0.000000 MBs
Jul 29 14:30:21 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:21.576Z INFO  bindex::chain] block=0000000000000000000231db5b7493f4e88b236e2fa9dfcd1b65a90adf135912 height=960116 headers loaded
Jul 29 14:30:22 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:22.098Z INFO  bindex::chain] block=000000000000000000011609b5476622bc279ca9fedea8852cb62bcb65776df2 height=960117: indexed 1 blocks, 1.873[MB], dt = 0.093[s]: 93.267 [ms/block], 1.873 [MB/block], 20.077 [MB/s]
Jul 29 14:30:23 jhb-gobserver-core-electrs electrs[107005]: [2026-07-29T14:30:23.106Z INFO  bindex::db] started auto compactions
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]: Error: electrs failed
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]: Caused by:
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:     0: sync failed
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:     1: RocksDB failed: IO error: While open a file for random read: /home/goss/Electrs/bitcoin/004814.sst: Too many open files
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:     2: IO error: While open a file for random read: /home/goss/Electrs/bitcoin/004814.sst: Too many open files
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]: Stack backtrace:
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    1: prometheus::histogram::Histogram::observe_closure_duration
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    2: electrs::server::run
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    3: std::sys::backtrace::__rust_begin_short_backtrace
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    4: std::rt::lang_start::{{closure}}
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    5: std::rt::lang_start_internal
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    6: main
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    7: <unknown>
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    8: __libc_start_main
Jul 29 14:58:14 jhb-gobserver-core-electrs electrs[107005]:    9: _start
Jul 29 14:58:14 jhb-gobserver-core-electrs systemd[823]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Jul 29 14:58:14 jhb-gobserver-core-electrs systemd[823]: electrs.service: Failed with result 'exit-code'.
Jul 29 14:58:14 jhb-gobserver-core-electrs systemd[823]: electrs.service: Consumed 1h 26min 16.019s CPU time, 4G memory peak.
Jul 29 14:59:14 jhb-gobserver-core-electrs systemd[823]: electrs.service: Scheduled restart job, restart counter is at 3.

```

I'm running electrs as a systemd user service, so I thought maybe that was an issue. But the file limits seem standard:

```bash
systemctl --user show electrs.service | grep NO
LimitNOFILE=524288
LimitNOFILESoft=1024
```

Not sure if the changes since 0.11.1 may have caused a regression here.
